export const preset = [
  {
    vex: "basic2D.vert",
    frag: "basic2D.frag",
    name: "图片-基础",
  },
  {
    vex: "basic2D.vert",
    frag: "gray.frag",
    name: "图片-灰度",
  },
  {
    vex: "basic2D.vert",
    frag: "blur.frag",
    name: "均值模糊（测试）",
  },
  {
    vex: "basic2D.vert",
    frag: "glitch.frag",
    name: "故障图像",
  },
];

export const note = [
  {
    attribute: "attribute",
    type: "vec3",
    name: "aPosition",
    description: "输入坐标",
  },
  {
    attribute: "attribute",
    type: "vec2",
    name: "aTexCoord",
    description: "顶点的纹理坐标",
  },
  {
    attribute: "uniform",
    type: "sampler2D",
    name: "uSampler",
    description: "纹理数据",
  },
  {
    attribute: "uniform",
    type: "vec2",
    name: "uResolution",
    description: "画布的大小",
  },
  {
    attribute: "uniform",
    type: "float",
    name: "uTime",
    description: "Shader 运行的时间（秒）",
  },
];

export const codeMirrorThemeNames = [
  "3024-day",
  "3024-night",
  "abbott",
  "abcdef",
  "ambiance-mobile",
  "ambiance",
  "ayu-dark",
  "ayu-mirage",
  "base16-dark",
  "base16-light",
  "bespin",
  "blackboard",
  "cobalt",
  "colorforth",
  "darcula",
  "dracula",
  "duotone-dark",
  "duotone-light",
  "eclipse",
  "elegant",
  "erlang-dark",
  "gruvbox-dark",
  "hopscotch",
  "icecoder",
  "idea",
  "isotope",
  "juejin",
  "lesser-dark",
  "liquibyte",
  "lucario",
  "material-darker",
  "material-ocean",
  "material-palenight",
  "material",
  "mbo",
  "mdn-like",
  "midnight",
  "monokai",
  "moxer",
  "neat",
  "neo",
  "night",
  "nord",
  "oceanic-next",
  "panda-syntax",
  "paraiso-dark",
  "paraiso-light",
  "pastel-on-dark",
  "railscasts",
  "rubyblue",
  "seti",
  "shadowfox",
  "solarized",
  "ssms",
  "the-matrix",
  "tomorrow-night-bright",
  "tomorrow-night-eighties",
  "ttcn",
  "twilight",
  "vibrant-ink",
  "xq-dark",
  "xq-light",
  "yeti",
  "yonce",
  "zenburn",
];
